#############################################
# Sambafiles - Compartilhamento de arquivos #
# Configuração: v1.0                        #
# Data: 06/10/22                            #
# Autor: Cairo Ap. Campos                   #
#############################################	

version: '2.4'
services:
  samba:
    ports:
      - "139:139"
      - "445:445"
    container_name: mysamba
    hostname: mysamba
    restart: always
    volumes:
      - mysamba_dados:/dados
      - mysamba_config:/etc/samba
    networks: 
      - default
    cpu_shares: 2000
    cpus: 1
    build: .
    image: mysamba:1.0

volumes:
   samba_dados:
      external: true
   samba_config:
      external: true

networks:
 default:
  external:
   name: network-mysamba
